[browser]
gatherUsageStats = false

[server]
enableCORS = false
enableXsrfProtection = false

[theme]
# 主题颜色 - 改为橙色系
primaryColor = "#FF8C42"           # 主橙色（原来是 #FF6B95 粉色）
backgroundColor = "#FFFBF7"        # 背景色改为浅橙色（原来是 #FFFAF9 粉色背景）
secondaryBackgroundColor = "#FFFFFF"
textColor = "#444444"
font = "Poppins"

# 组件样式
[theme.button]
backgroundColor = "#FF8C42"        # 按钮背景改为橙色（原来是 #FF6B95 粉色）
textColor = "#FFFFFF"
borderRadius = "30px"

[theme.selectbox]
backgroundColor = "#FFFFFF"
textColor = "#444444"
borderRadius = "30px"

[theme.slider]
backgroundColor = "#FFFFFF"
textColor = "#444444"
borderRadius = "30px"

# 布局设置
[theme.layout]
padding = "3rem"
maxWidth = "1200px"